apiVersion: apps/v1
kind: Deployment
metadata:
  name: leads
  labels:
    app: leads
spec:
  replicas: 1
  selector:
    matchLabels:
      name: leads
  template:
    metadata:
      labels:
        name: leads
    spec:
      containers:
        - name: leads
          image: django-skeleton:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "leads"
            - name: DATABASE_URL
              value: psql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB) #postgres here must match the PostgreSQL service name you created earlier

---
# START Service
apiVersion: v1
kind: Service
metadata:
  name: leads
  labels:
    app: leads
spec:
  type: LoadBalancer
  ports:
    - port: 80 #port that the service exposes
      targetPort: 8000 #port that the app is receiving requests from via the pod
  selector:
    name: leads
# END SERVICE